age = input("Введите свой возраст:")
height = input("Введите свой рост:")
name = input("Введите свое имя:")
sex = input("Введите свой пол:")
fullname = input("Введите свою фамилию:")
profession = input("Введите свою профессию:")
kids = input("Есть ли у вас дети?:")
family = input("Есть брат\сестра?:")
hobby = input("Какое у вас хобби?:")
print("Возраст:" + age)
print("Рост:" + height)
print("Имя:" + name)
print("Пол:" + sex)
print("Фамилия:" + fullname)
print("Профессия:" + profession)
print("Дети:" + kids)
print("Брат/сестра:" + family)
print("Хобби:" + hobby)

